### ISSUE TITLE
关于内部 magic依赖里的问题

### ISSUE THREAD

**Issue by yanyuyoulan** [gumblex/extract-gk100d#2]
在您所写的提取文件py文件中的第146行有如下一句话
fmagic = magic.detect_from_data(data)
但是我在您标注的依赖 python3-magic中并没有发现这一个函数的定义
并且在我的环境中运行时产生了错误
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\gaokao100\extractdata.py", line 229, in <module>
    main()
  File "D:\SteamLibrary\steamapps\common\gaokao100\extractdata.py", line 226, in main
    xp3file.extract(args[1])
  File "D:\SteamLibrary\steamapps\common\gaokao100\extractdata.py", line 135, in extract
    ext = self.detect_ext(outbuffer.read(1024))
  File "D:\SteamLibrary\steamapps\common\gaokao100\extractdata.py", line 146, in detect_ext
    fmagic = magic.detect_from_data(data)
AttributeError: module 'magic' has no attribute 'detect_from_data'

进程已结束,退出代码1
我的参数是  -e bgm.xp3 output/
根据CSDN的反馈 我已经重装过magic 以及magic的windowsDLL依赖
但是我还是无法顺利运行  可以帮帮我吗 谢谢

**Comment by Limour-dev** [comment]
https://github.com/ahupp/python-magic/blob/master/COMPAT.md

detect_from_content => from_buffer

**Comment by Limour-dev** [comment]
```powershell
conda create -n gk100d conda-forge::python
conda activate gk100d
pip install python-magic-bin
python extractdata.py -e data.xp3 output/
conda remove -n gk100d --all
```
```python
    def detect_ext(self, data):
        import magic
        fmagic = magic.from_buffer(data, mime=True)
        print(fmagic)
        if fmagic.startswith('text/'):
            return '.bin'
            if fmagic.encoding == 'unknown-8bit':
                ext = '.bin'
            else:
                text = data.decode(fmagic.encoding)
                if '@return' in text or '*start' in text or '.ks' in text or '[w]' in text:
                    ext = '.ks'
                elif '.tjs' in text or '%[' in text or '];' in text:
                    ext = '.tjs'
                else:
                    ext = '.txt'
        else:
            ext = mimetypes.guess_extension(fmagic)
            if ext == '.jpeg':
                ext = '.jpg'
            elif ext == '.oga':
                ext = '.ogg'
            elif ext == '.asf':
                ext = '.wmv'
        return ext
```

**Comment by Limour-dev** [comment]
```powershell
conda create -n gk100d conda-forge::python
conda activate gk100d
pip install python-magic-bin
pip install python-magic
pip show python-magic
```
+ 打开 envs\gk100d\Lib\site-packages\magic
+ 修改 `loader.py` ，在 `def _lib_candidates():` 中添加
```python
def _lib_candidates():
  yield r'C:\Users\limou\miniconda3\envs\gk100d\Lib\site-packages\magic\libmagic\libmagic.dll'
```
```powershell
python extractdata.py -e data.xp3 output/
conda remove -n gk100d --all
```
+ 另外有些检测不了类型的错误，可以跳过
```python
    def detect_ext(self, data):
        import magic
        try:
            fmagic = magic.detect_from_content(data)
        except AttributeError as e:
            print(e)
            return '.ukn'
```
+ 解包结果

![image](https://github.com/user-attachments/assets/8549e731-50d5-4bfa-8853-9e530609bdd7)

+ 一些没有识别的类型可能为
```txt
.bin > TVP pre-rendered font
.txt > BMP | .tjs
.ukn > .tjs
```
